/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"


double
calculator_prog_1(char *host,double x, double y, char cal, CLIENT * clnt)
{
	double  *result_1;
	numbers  add_1_arg;
	double  *result_2;
	numbers  sub_1_arg;
	double  *result_3;
	numbers  mul_1_arg;
	double  *result_4;
	numbers  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATOR_PROG, CALCULATOR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if(cal=='+'){
		add_1_arg.a=x;
		add_1_arg.b=y;
		add_1_arg.sign=cal;
		//printf("%lf %c %lf\n",x,cal,y);
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_1;
	}
	else if(cal=='-'){
		sub_1_arg.a=x;
        sub_1_arg.b=y;
        sub_1_arg.sign=cal;
		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_2;
	}
	else if(cal=='*'){
		mul_1_arg.a=x;
        mul_1_arg.b=y;
        mul_1_arg.sign=cal;
		result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_3;
	}
	else if(cal=='/'){
		div_1_arg.a=x;
        div_1_arg.b=y;
        div_1_arg.sign=cal;
		result_4 = div_1(&div_1_arg, clnt);
		if (result_4 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else{
		printf("...\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;
	double a,b;
	char cal;
	int tmp;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clnt = clnt_create(host, CALCULATOR_PROG, CALCULATOR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit(1);
	}
	scanf("%lf%c%lf",&a,&cal,&b);
	//printf("%lf %c %lf",a,cal,b);
	printf("The answer is %lf\n" ,calculator_prog_1 (host,a,b,cal,clnt));
exit (0);
}
