/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rand.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->sign))
		 return FALSE;
	return TRUE;
}
