/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

double *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	//printf("%lf %c %lf\n",argp->a,argp->sign,argp->b);	
	printf("add(%lf, %lf) is called\n", argp->a, argp->b);
	result = argp->a+argp->b;

	return &result;
}

double *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	printf("sub(%lf, %lf) is called\n", argp->a, argp->b);
	result = argp->a-argp->b;

	return &result;
}

double *
mul_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */

	printf("mul(%lf, %lf) is called\n", argp->a, argp->b);
	result = argp->a*argp->b;	

	return &result;
}

double *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	printf("div(%lf, %lf) is called\n", argp->a, argp->b);
	result = argp->a/argp->b;

	return &result;
}
