/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RAND_H_RPCGEN
#define _RAND_H_RPCGEN

#include <rpc/rpc.h>
#include <math.h>
#include <stdio.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	double a;
	double b;
	char sign;
};
typedef struct numbers numbers;

#define CALCULATOR_PROG 0x31111111
#define CALCULATOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  double * add_1(numbers *, CLIENT *);
extern  double * add_1_svc(numbers *, struct svc_req *);
#define sub 2
extern  double * sub_1(numbers *, CLIENT *);
extern  double * sub_1_svc(numbers *, struct svc_req *);
#define mul 3
extern  double * mul_1(numbers *, CLIENT *);
extern  double * mul_1_svc(numbers *, struct svc_req *);
#define div 4
extern  double * div_1(numbers *, CLIENT *);
extern  double * div_1_svc(numbers *, struct svc_req *);
extern int calculator_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  double * add_1();
extern  double * add_1_svc();
#define sub 2
extern  double * sub_1();
extern  double * sub_1_svc();
#define mul 3
extern  double * mul_1();
extern  double * mul_1_svc();
#define div 4
extern  double * div_1();
extern  double * div_1_svc();
extern int calculator_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RAND_H_RPCGEN */
